language: node_js

node_js:
- '8'

install:
- npm install
- npm install --save @kaiu/serializer

script: npm test

notifications:
  email: false

after_success:
- npm run codecov

addons:
  chrome: stable

dist: trusty
